export const enum EActionsApi {
  REQUEST = 'REQUEST',
  SET_REQUEST = 'SET_REQUEST',
  DELETE_REQUEST = 'DELETE_REQUEST',
  CANCEL_REQUEST = 'CANCEL_REQUEST',
  CANCEL_ALL_REQUESTS = 'CANCEL_ALL_REQUESTS',
}
